### ISSUE TITLE
1.5 Herencia: Parte 1 (3 PERSONAS)

### ISSUE THREAD

**Issue by facundoPereyra07** [CodeSystem2022/Team-Fortran-2023#128]
- [x] Diagrama UML 1 ( PRIMER CUADRO)
- [x] Diagrama UML 2 ( SEGUNDO CUADRO)
- [x] Codigo luego de los diagramas ( a partir de min 3:00)

**Comment by HidoGG** [comment]
Tomo la ultima parte Pao. "Codigo luego de los diagramas ( a partir de min 3:00)"
