### ISSUE TITLE
1.2 Ejercicio: Sobreescritura de métodos Overriding Parte 1 y 2

### ISSUE THREAD

**Issue by danisa-morales** [CodeSystem2022/Team-Fortran-2023#66]
- [x] 1.2  PARTE 1
- [x] 1.2  PARTE 2

**Comment by pao2134** [comment]
Ya se encuentran los dos puntos subidos

**Comment by danisa-morales** [comment]
Se reabre el Issue, hasta que se realice el Pull requests

**Comment by pao2134** [comment]
Se cierra el issue
